language: node_js

node_js:
  - "8.10.0"

sudo: true

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - mysql

before_script:
  - cp ./migrations/config.js.travis ./migrations/config.js
  - cp ./config/.env.travis ./config/.env
  - mysql -e "CREATE DATABASE picsart_test;"
  - node_modules/.bin/sequelize --config ./migrations/config.js --migrations-path ./migrations/migrations db:migrate

